bmi-era5:
  name: reanalysis-era5-pressure-levels
  request:
    variable:
      - u_component_of_wind
      - v_component_of_wind
    pressure_level:
      - 1
      - 5
    product_type: ensemble_members
    year: 2021
    month: 01
    day: 01
    time:
      - 00:00
      - 03:00
      - 06:00
    format: netcdf
    area:
      - 41
      - -109
      - 36
      - -102
    grid:
      - 0.5
      - 0.5
  path: pressure_hour_enm.nc
